### ISSUE TITLE
Could not find type or Namespaces

### ISSUE THREAD

**Issue by Chookees** [thedraken/DistSerMW#1]
Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0246	The type or namespace name 'AustinHarris' could not be found (are you missing a using directive or an assembly reference?)	Gambler	\DistSerMW-master\C#\Gambler\Gambler\Model\RPC\Common\JsonRpcConnection.cs	1	Active

Error	CS0246	The type or namespace name 'JsonResponse' could not be found (are you missing a using directive or an assembly reference?)	Gambler	\DistSerMW-master\C#\Gambler\Gambler\Model\RPC\Common\JsonRpcConnection.cs	102	Active

Error	CS0246	The type or namespace name 'AustinHarris' could not be found (are you missing a using directive or an assembly reference?)	Gambler	\DistSerMW-master\C#\Gambler\Gambler\Model\RPC\GamblerServer.cs	1	Active

Error	CS0246	The type or namespace name 'JsonResponse' could not be found (are you missing a using directive or an assembly reference?)	Gambler	DistSerMW-master\C#\Gambler\Gambler\Model\RPC\GamblerServer.cs	94	Active

Error	CS0246	The type or namespace name 'JsonRequest' could not be found (are you missing a using directive or an assembly reference?)	Gambler	DistSerMW-master\C#\Gambler\Gambler\Model\RPC\GamblerServer.cs	94	Active

Error	CS0246	The type or namespace name 'JsonRequest' could not be found (are you missing a using directive or an assembly reference?)	Gambler	DistSerMW-master\C#\Gambler\Gambler\Model\RPC\GamblerServer.cs	117	Active
Error	CS0246	The type or namespace name 'JsonResponse' could not be found (are you missing a using directive or an assembly reference?)	Gambler	DistSerMW-master\C#\Gambler\Gambler\Model\RPC\GamblerServer.cs	117	Active

Error	CS0246	The type or namespace name 'JsonRequest' could not be found (are you missing a using directive or an assembly reference?)	Gambler	DistSerMW-master\C#\Gambler\Gambler\Model\RPC\GamblerServer.cs	135	Active

Error	CS0246	The type or namespace name 'JsonResponse' could not be found (are you missing a using directive or an assembly reference?)	Gambler	DistSerMW-master\C#\Gambler\Gambler\Model\RPC\GamblerServer.cs	135	Active

Error	CS0246	The type or namespace name 'JsonRequest' could not be found (are you missing a using directive or an assembly reference?)	Gambler	DistSerMW-master\C#\Gambler\Gambler\Model\RPC\GamblerServer.cs	140	Active

Error	CS0246	The type or namespace name 'JsonResponse' could not be found (are you missing a using directive or an assembly reference?)	Gambler	DistSerMW-master\C#\Gambler\Gambler\Model\RPC\GamblerServer.cs	141	Active

Error	CS0246	The type or namespace name 'JsonRpcService' could not be found (are you missing a using directive or an assembly reference?)	Gambler	DistSerMW-master\C#\Gambler\Gambler\Model\RPC\GamblerServer.cs	148	Active

Error	CS0246	The type or namespace name 'JsonRpcMethodAttribute' could not be found (are you missing a using directive or an assembly reference?)	Gambler	DistSerMW-master\C#\Gambler\Gambler\Model\RPC\GamblerServer.cs	161	Active

Error	CS0246	The type or namespace name 'JsonRpcMethod' could not be found (are you missing a using directive or an assembly reference?)	Gambler	DistSerMW-master\C#\Gambler\Gambler\Model\RPC\GamblerServer.cs	161	Active

CS0246	The type or namespace name 'JsonRpcMethodAttribute' could not be found (are you missing a using directive or an assembly reference?)	Gambler	DistSerMW-master\C#\Gambler\Gambler\Model\RPC\GamblerServer.cs	176	Active

Error	CS0246	The type or namespace name 'JsonRpcMethod' could not be found (are you missing a using directive or an assembly reference?)	Gambler	DistSerMW-master\C#\Gambler\Gambler\Model\RPC\GamblerServer.cs	176	Active

Error	CS0246	The type or namespace name 'JsonRpcMethodAttribute' could not be found (are you missing a using directive or an assembly reference?)	Gambler	DistSerMW-master\C#\Gambler\Gambler\Model\RPC\GamblerServer.cs	230	Active

Error	CS0246	The type or namespace name 'JsonRpcMethod' could not be found (are you missing a using directive or an assembly reference?)	Gambler	DistSerMW-master\C#\Gambler\Gambler\Model\RPC\GamblerServer.cs	230	Active

Error	CS0246	The type or namespace name 'JsonRpcMethodAttribute' could not be found (are you missing a using directive or an assembly reference?)	Gambler	DistSerMW-master\C#\Gambler\Gambler\Model\RPC\GamblerServer.cs	245	Active

Error	CS0246	The type or namespace name 'JsonRpcMethod' could not be found (are you missing a using directive or an assembly reference?)	Gambler	DistSerMW-master\C#\Gambler\Gambler\Model\RPC\GamblerServer.cs	245	Active

Error	CS0246	The type or namespace name 'JsonRpcMethodAttribute' could not be found (are you missing a using directive or an assembly reference?)	Gambler	DistSerMW-master\C#\Gambler\Gambler\Model\RPC\GamblerServer.cs	257	Active

Error	CS0246	The type or namespace name 'JsonRpcMethod' could not be found (are you missing a using directive or an assembly reference?)	Gambler	DistSerMW-master\C#\Gambler\Gambler\Model\RPC\GamblerServer.cs	257	Active

Error	CS0246	The type or namespace name 'AustinHarris' could not be found (are you missing a using directive or an assembly reference?)	Gambler	DistSerMW-master\C#\Gambler\Gambler\Model\RPC\JSONRPCServer\JsonRPCSocketServer.cs	1	Active

Error	CS0246	The type or namespace name 'JsonRpcService' could not be found (are you missing a using directive or an assembly reference?)	Gambler	DistSerMW-master\C#\Gambler\Gambler\Model\RPC\JSONRPCServer\JsonRPCSocketServer.cs	20	Active

Error	CS0246	The type or namespace name 'JsonRpcMethodAttribute' could not be found (are you missing a using directive or an assembly reference?)	Gambler	DistSerMW-master\C#\Gambler\Gambler\Model\RPC\JSONRPCServer\JsonRPCSocketServer.cs	33	Active

Error	CS0246	The type or namespace name 'JsonRpcMethod' could not be found (are you missing a using directive or an assembly reference?)	Gambler	DistSerMW-master\C#\Gambler\Gambler\Model\RPC\JSONRPCServer\JsonRPCSocketServer.cs	33	Active

Error	CS0246	The type or namespace name 'JsonResponse' could not be found (are you missing a using directive or an assembly reference?)	Gambler	DistSerMW-master\C#\Gambler\Gambler\Model\RPC\JSONRPCServer\JsonRPCSocketServer.cs	81	Active

Error	CS0246	The type or namespace name 'JsonRequest' could not be found (are you missing a using directive or an assembly reference?)	Gambler	DistSerMW-master\C#\Gambler\Gambler\Model\RPC\JSONRPCServer\JsonRPCSocketServer.cs	81	Active

Error	CS0246	The type or namespace name 'JsonRequest' could not be found (are you missing a using directive or an assembly reference?)	Gambler	DistSerMW-master\C#\Gambler\Gambler\Model\RPC\JSONRPCServer\JsonRPCSocketServer.cs	88	Active

Error	CS0246	The type or namespace name 'JsonResponse' could not be found (are you missing a using directive or an assembly reference?)	Gambler	DistSerMW-master\C#\Gambler\Gambler\Model\RPC\JSONRPCServer\JsonRPCSocketServer.cs	88	Active

Error	CS0246	The type or namespace name 'AustinHarris' could not be found (are you missing a using directive or an assembly reference?)	Gambler	DistSerMW-master\C#\Gambler\Gambler\Model\RPC\BookieConnection.cs	1	Active

Error	CS0246	The type or namespace name 'AustinHarris' could not be found (are you missing a using directive or an assembly reference?)	Gambler	DistSerMW-master\C#\Gambler\Gambler\Model\RPC\BookieConnection.cs	1	Active

Error	CS0246	The type or namespace name 'JsonResponse' could not be found (are you missing a using directive or an assembly reference?)	Gambler	DistSerMW-master\C#\Gambler\Gambler\Model\RPC\BookieConnection.cs	166	Active

Error	CS0246	The type or namespace name 'JsonResponse' could not be found (are you missing a using directive or an assembly reference?)	Gambler	DistSerMW-master\C#\Gambler\Gambler\Model\RPC\BookieConnection.cs	34	Active

Error	CS0246	The type or namespace name 'JsonResponse' could not be found (are you missing a using directive or an assembly reference?)	Gambler	DistSerMW-master\C#\Gambler\Gambler\Model\RPC\BookieConnection.cs	49	Active

Error	CS0246	The type or namespace name 'JsonResponse' could not be found (are you missing a using directive or an assembly reference?)	Gambler	DistSerMW-master\C#\Gambler\Gambler\Model\RPC\BookieConnection.cs	66	Active

Error	CS0246	The type or namespace name 'JsonResponse' could not be found (are you missing a using directive or an assembly reference?)	Gambler	DistSerMW-master\C#\Gambler\Gambler\Model\RPC\BookieConnection.cs	96	Active

Error	CS0246	The type or namespace name 'JsonResponse' could not be found (are you missing a using directive or an assembly reference?)	Gambler	DistSerMW-master\C#\Gambler\Gambler\Model\RPC\BookieConnection.cs	120	Active

Error	CS0246	The type or namespace name 'JsonResponse' could not be found (are you missing a using directive or an assembly reference?)	Gambler	DistSerMW-master\C#\Gambler\Gambler\Model\RPC\BookieConnection.cs	188	Active

Error	CS0246	The type or namespace name 'JsonResponse' could not be found (are you missing a using directive or an assembly reference?)	Gambler	DistSerMW-master\C#\Gambler\Gambler\Model\RPC\BookieConnection.cs	233	Active

**Comment by thedraken** [comment]
This was a university project and required other dependencies to run that are not released to the public. This will not be fixed.
